# Generated by Django 4.2 on 2023-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_web_site', '0002_remove_newuser_user_credit_card_delete_creditcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='images.png', upload_to='photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
