# Generated by Django 4.2 on 2023-04-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_web_site', '0003_alter_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
    ]
